#!/bin/sh
find ./lib/*.jar | xargs -I % sh -c 'mvn install:install-file -Dfile=% \
  -DgroupId=org.apache.struts \
  -DartifactId=struts1 \
  -Dpackaging=jar \
  -Dversion=1.3.10 \
  -DgeneratePom=true
'
